import { cn } from "@/lib/utils";
import { bg, px } from "@/styles/constants";
import "@/styles/globals.css";
import "@/styles/prism.css";
import "@/styles/socials.css";
import Footer from "../components/Footer";
import Header from "../components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col",
          "h-screen",
          "max-w-screen-md mx-auto",
          bg
        )}
      >
        <Header />
        <main className={cn("flex-grow", px)}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
